apiVersion: v1
kind: ConfigMap
metadata:
  name: flowforge-config
  namespace: flowforge
data:
  ASPNETCORE_URLS: "http://+:8080"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ELASTICSEARCH_URI: "http://elasticsearch:9200"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: flowforge
data:
  init.sql: |
    CREATE DATABASE control_db;
    CREATE DATABASE worker_db;
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: flowforge
type: Opaque
stringData:
  POSTGRES_PASSWORD: "flowforge"
