apiVersion: apps/v1
kind: Deployment
metadata:
  name: logindexer
  namespace: flowforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logindexer
  template:
    metadata:
      labels:
        app: logindexer
    spec:
      containers:
        - name: logindexer
          image: flowforge-logindexer:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "tr '\\0' ' ' </proc/1/cmdline | grep -q FlowForge.LogIndexer.dll"
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: Kafka__BootstrapServers
              valueFrom:
                configMapKeyRef:
                  name: flowforge-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: Elasticsearch__Uri
              valueFrom:
                configMapKeyRef:
                  name: flowforge-config
                  key: ELASTICSEARCH_URI
